import {HEROES,STAGES,CHAPTERS,Hero,StatusKind,Bond} from './data';
import {Save,Owned,stats,activeBonds,own} from './state';
export interface Unit {uid:string;hero:number;side:0|1;slot:number;level:number;hp:number;maxHp:number;atk:number;def:number;mdef:number;speed:number;crit:number;critDamage:number;skillScale:number;rage:number;shield:number;statuses:Partial<Record<StatusKind,number>>;boss:boolean;damage:number;healing:number}
export interface NumberHit {uid:string;value:number;kind:'damage'|'critical'|'heal'|'dot'|'shield';}
export interface BattleEvent {kind:'intro'|'attack'|'skill'|'combo'|'status'|'boss'|'end';round:number;actor?:string;partners?:number[];targets:string[];hits:NumberHit[];label:string;element:string;units:Unit[];winner?:0|1;stars?:number;comboId?:string}
export interface BattleResult {events:BattleEvent[];winner:0|1;stars:number;rounds:number;units:Unit[]}
export function seeded(seed:number){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function simulate(s:Save,stageId:number,seed=Math.floor(Math.random()*1e8)):BattleResult {
const st=STAGES[stageId],rng=seeded(seed),bonds=activeBonds(s.formation),units:Unit[]=[],events:BattleEvent[]=[];let round=0,comboRound=-1;
const make=(id:number,side:0|1,slot:number,o:Owned):Unit=>{const x=stats(HEROES[id],o),boss=side===1&&st.boss&&slot===3;const atkBonus=side===0?bonds.reduce((a,b)=>a+(b.atk||0),0):0,hpBonus=side===0?bonds.reduce((a,b)=>a+(b.hp||0),0):0;const enemyScale=side===1?(.56+Math.min(stageId,20)*.013):1;const maxHp=Math.round(x.hp*(1+hpBonus)*enemyScale*(boss?2.35:1));return{uid:`${side}-${slot}`,hero:id,side,slot,level:o.level,hp:maxHp,maxHp,atk:Math.round(x.atk*(1+atkBonus)*enemyScale*(boss?1.18:1)),def:Math.round(x.def*enemyScale),mdef:Math.round(x.mdef*enemyScale),speed:x.speed,crit:x.crit,critDamage:x.critDamage,skillScale:x.skillScale,rage:30,shield:side===0&&bonds.some(b=>b.id==='wall')?Math.round(maxHp*.15):0,statuses:{},boss,damage:0,healing:0};};
s.formation.forEach((id,i)=>units.push(make(id,0,i,s.roster[id])));st.enemies.forEach((id,i)=>units.push(make(id,1,i,{...own(id),level:st.level,stars:st.chapter>=3?2:1,ascend:st.chapter>=2?1:0})));
const alive=(side:number)=>units.filter(u=>u.side===side&&u.hp>0);const snap=()=>units.map(u=>({...u,statuses:{...u.statuses}}));const emit=(e:Omit<BattleEvent,'round'|'units'>)=>events.push({...e,round,units:snap()});
const applyStatus=(t:Unit,k:StatusKind,d=2)=>{t.statuses[k]=Math.max(t.statuses[k]||0,d);};
const damage=(a:Unit,t:Unit,power:number,magical:boolean,hits:NumberHit[],kind:'damage'|'dot'='damage')=>{if(t.hp<=0)return;const critical=kind!=='dot'&&rng()<a.crit;const defense=(magical?t.mdef:t.def)*(t.statuses.defdown?.7:1);const buff=a.statuses.attack?1.25:1;let value=kind==='dot'?power:Math.round(a.atk*buff*power*(420/(420+defense))*(critical?a.critDamage:1)*(.94+rng()*.12));if(kind!=='dot'&&a.hero===1&&t.hp/t.maxHp<.35)value=Math.round(value*1.5);value=Math.max(1,Math.round(value));const blocked=Math.min(t.shield,value);t.shield-=blocked;const actual=Math.min(t.hp,value-blocked);t.hp=Math.max(0,t.hp-actual);a.damage+=actual;t.rage=Math.min(100,t.rage+8);hits.push({uid:t.uid,value:actual||blocked,kind:actual?(kind==='dot'?'dot':critical?'critical':'damage'):'shield'});};
const heal=(a:Unit,t:Unit,value:number,hits:NumberHit[])=>{if(t.hp<=0)return;const amount=Math.min(t.maxHp-t.hp,Math.round(value));t.hp+=amount;a.healing+=amount;hits.push({uid:t.uid,value:amount,kind:'heal'});};
const pick=(a:Unit,target:string)=>{const foes=alive(1-a.side),friends=alive(a.side),front=foes.filter(t=>t.slot<3),back=foes.filter(t=>t.slot>=3);if(target==='ally')return friends;if(target==='self')return[a];if(target==='all')return foes;if(target==='front')return front.length?front:foes;if(target==='back')return back.length?back:foes;if(target==='lowest')return foes.sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp).slice(0,1);if(target==='random')return foes.map(u=>({u,k:rng()})).sort((a,b)=>a.k-b.k).slice(0,3).map(a=>a.u);const taunt=foes.find(t=>t.statuses.taunt);return taunt?[taunt]:(front.length?front:foes).slice(0,1);};
const comboUsed:Record<string,number>={},firstSkills=new Set<string>();let enraged=false;
emit({kind:'intro',targets:[],hits:[],label:st.boss?`${CHAPTERS[st.chapter].mechanic} · 决战开始`:'列阵 · 出征',element:st.boss?'shadow':'wind'});
for(round=1;round<=20;round++){
if(!alive(0).length||!alive(1).length)break;
const boss=alive(1).find(u=>u.boss);
if(boss){const hits:NumberHit[]=[];let label='';if(st.chapter===0&&round%3===0){alive(0).forEach(t=>damage(boss,t,.9,true,hits));const t=alive(0)[Math.floor(rng()*alive(0).length)];if(t)applyStatus(t,'stun',1);label='苍天雷罚';}if(st.chapter===1&&!enraged&&boss.hp/boss.maxHp<.5){enraged=true;boss.atk=Math.round(boss.atk*1.4);label='无双狂怒 · 攻击提升40%';}if(st.chapter===2&&[2,4,6].includes(round)){const fallen=units.find(u=>u.side===1&&u.hp===0&&!u.boss);if(fallen){fallen.hp=Math.round(fallen.maxHp*.4);fallen.statuses={};hits.push({uid:fallen.uid,value:fallen.hp,kind:'heal'});}else alive(1).forEach(t=>heal(boss,t,t.maxHp*.08,hits));label='千军援阵 · 旌旗不倒';}if(st.chapter===3&&round%3===0){alive(1).forEach(t=>applyStatus(t,'attack',3));alive(0).filter(t=>t.slot>=3).forEach(t=>applyStatus(t,'silence',1));label='魏武号令';}if(st.chapter===4&&round%2===0){alive(0).forEach(t=>{applyStatus(t,'burn',2);damage(boss,t,.45,true,hits);});label='赤壁业火';}if(label)emit({kind:'boss',actor:boss.uid,targets:hits.map(h=>h.uid),hits,label,element:st.chapter===4?'fire':st.chapter===0?'thunder':'shadow'});}
const order=units.filter(u=>u.hp>0).sort((a,b)=>b.speed-a.speed||a.side-b.side);
for(const a of order){if(a.hp<=0||!alive(0).length||!alive(1).length)continue;
const ticks:NumberHit[]=[];for(const k of ['burn','poison'] as const){if(a.statuses[k]){const source=alive(1-a.side)[0];if(source)damage(source,a,a.maxHp*(k==='burn'&&a.side===1&&bonds.some(b=>b.id==='fire')?.12:.08),true,ticks,'dot');}}if(ticks.length)emit({kind:'status',actor:a.uid,targets:[a.uid],hits:ticks,label:a.statuses.burn?'灼烧':'中毒',element:a.statuses.burn?'fire':'shadow'});if(a.hp<=0)continue;
if(a.statuses.stun){emit({kind:'status',actor:a.uid,targets:[a.uid],hits:[],label:'眩晕 · 无法行动',element:'thunder'});for(const k of Object.keys(a.statuses) as StatusKind[]){a.statuses[k]=(a.statuses[k]||0)-1;if(!a.statuses[k])delete a.statuses[k];}continue;}
const h=HEROES[a.hero];const combo=a.side===0&&comboRound!==round?bonds.find(b=>b.combo&&b.heroes.includes(a.hero)&&(comboUsed[b.id]===undefined||round-comboUsed[b.id]>=3)&&b.heroes.every(id=>alive(0).some(u=>u.hero===id&&u.rage>=70&&!u.statuses.stun&&!u.statuses.silence))):undefined;
if(combo){comboRound=round;comboUsed[combo.id]=round;const pair=alive(0).filter(u=>combo.heroes.includes(u.hero));pair.forEach(u=>u.rage=Math.max(0,u.rage-70));const hits:NumberHit[]=[];const targets=combo.effect==='heal'?alive(0):pick(a,combo.effect==='execute'?'lowest':combo.target||'all');targets.forEach(t=>{if(combo.effect==='heal'){heal(a,t,t.maxHp*.32,hits);t.shield+=Math.round(t.maxHp*.18);}else{damage(a,t,combo.power||2,false,hits);if(combo.effect==='burn')applyStatus(t,'burn');if(combo.effect==='stun'&&t.slot<3)applyStatus(t,'stun',1);}});if(combo.effect==='shield')alive(0).forEach(t=>t.shield+=Math.round(t.maxHp*.18));if(combo.effect==='energy')alive(0).forEach(t=>t.rage=Math.min(100,t.rage+30));if(combo.id==='moon')heal(a,a,hits.reduce((x,t)=>x+t.value,0)*.2,hits);emit({kind:'combo',actor:a.uid,partners:combo.heroes,targets:targets.map(t=>t.uid),hits,label:combo.combo!,element:combo.element,comboId:combo.id});}
else if(a.rage>=100&&!a.statuses.silence){a.rage=0;const sk=h.skill,targets=pick(a,sk.target),hits:NumberHit[]=[];for(let n=0;n<(sk.hits||1);n++)targets.forEach(t=>{if(sk.heal)heal(a,t,a.atk*sk.heal*a.skillScale,hits);else damage(a,t,sk.power*a.skillScale,h.role==='谋士'||h.role==='辅助',hits);if(sk.status&&t.hp>0){if(sk.status==='shield')t.shield+=Math.round(a.maxHp*.18);else if(sk.status==='taunt'){applyStatus(a,'taunt',3);a.shield=Math.max(a.shield,Math.round(a.maxHp*.25));}else if(sk.status==='attack')applyStatus(sk.target==='ally'?t:a,'attack',3);else if(sk.status!=='stun'||![3,20].includes(a.hero)||rng()<.35)applyStatus(t,sk.status,['stun','silence'].includes(sk.status)?1:2);}if(sk.energy)t.rage=Math.min(100,t.rage+sk.energy);if(a.hero===13){delete t.statuses.burn;delete t.statuses.poison;}});if(sk.leech)heal(a,a,hits.reduce((x,t)=>x+t.value,0)*sk.leech,hits);if(a.hero===6)alive(a.side).forEach(t=>applyStatus(t,'attack',3));if(a.hero===19){const t=alive(a.side).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(t)heal(a,t,a.atk*2.5,hits);}if(a.side===0&&bonds.some(b=>b.id==='tactician')&&!firstSkills.has(a.uid))a.rage=Math.min(100,a.rage+35);firstSkills.add(a.uid);emit({kind:'skill',actor:a.uid,targets:targets.map(t=>t.uid),hits,label:sk.name,element:sk.element});}
else{const targets=pick(a,'normal'),hits:NumberHit[]=[];targets.forEach(t=>damage(a,t,1,h.role==='谋士',hits));a.rage=Math.min(100,a.rage+45);emit({kind:'attack',actor:a.uid,targets:targets.map(t=>t.uid),hits,label:`${h.name} · ${h.role==='谋士'?'术击':'普攻'}`,element:h.skill.element});}
for(const k of Object.keys(a.statuses) as StatusKind[]){a.statuses[k]=(a.statuses[k]||0)-1;if(!a.statuses[k])delete a.statuses[k];}
}
}
const winner:0|1=alive(0).length>0&&alive(1).length===0?0:1;const rounds=Math.min(round-1,20);const stars=winner===0?1+(alive(0).length===6?1:0)+(rounds<=10?1:0):0;round=rounds;emit({kind:'end',targets:[],hits:[],label:winner===0?'大获全胜':'胜败乃兵家常事',element:winner===0?'light':'shadow',winner,stars});return{events,winner,stars,rounds,units:snap()};}
