import {HEROES,BONDS,STAGES,Hero} from './data';
export interface Owned {id:number;level:number;stars:number;ascend:number;shards:number}
export interface Save {version:2;name:string;started:boolean;gold:number;exp:number;tickets:number;stones:number;roster:Record<number,Owned>;shardBank:Record<number,number>;formation:number[];cleared:Record<number,number>;pulls:number;pity:number;daily:string;claimed:string[];wins:number;upgrades:number;sound:boolean;dev:boolean;effects?:'full'|'reduced';musicVolume?:number;sfxVolume?:number}
export const SAVE_KEY='yunque-sanguo-v2';
export const own=(id:number):Owned=>({id,level:1,stars:1,ascend:0,shards:0});
export function fresh():Save{return{version:2,name:'云游少主',started:false,gold:18000,exp:240,tickets:20,stones:30,shardBank:{},roster:Object.fromEntries([0,1,2,4,5,13].map(id=>[id,own(id)])),formation:[2,1,5,0,4,13],cleared:{},pulls:0,pity:0,daily:'',claimed:[],wins:0,upgrades:0,sound:true,dev:false};}
export const clone=(s:Save):Save=>JSON.parse(JSON.stringify(s));
export function loadSave():Save{try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(raw?.version===2&&raw.roster&&Array.isArray(raw.formation)&&raw.formation.length===6){const s={...fresh(),...raw};if(s.formation.every((n:number)=>Number.isInteger(n)&&HEROES[n]&&s.roster[n])&&new Set(s.formation).size===6&&['gold','exp','tickets','stones'].every(k=>Number.isFinite(s[k])&&s[k]>=0))return s;}}catch{}return fresh();}
export function activeBonds(formation:number[]){return BONDS.filter(b=>b.heroes.every(id=>formation.includes(id)));}
export function stats(h:Hero,o:Owned){const rarity={R:1,SR:1.06,SSR:1.12,UR:1.2}[h.rarity];const scale=(1+(o.level-1)*.105)*(1+(o.stars-1)*.15)*(1+o.ascend*.14)*rarity;return{hp:Math.round(h.hp*scale),atk:Math.round(h.atk*scale),def:Math.round(h.def*scale),mdef:Math.round(h.mdef*scale),speed:h.speed+o.level+o.ascend*3,crit:h.crit+(o.stars>=3?.06:0)+(o.ascend>=2?.05:0),critDamage:1.5+(o.stars>=5?.25:0),skillScale:o.stars>=3?1.2:1};}
export function heroPower(o:Owned){const x=stats(HEROES[o.id],o);return Math.round(x.hp*.22+x.atk*3.5+(x.def+x.mdef)*1.3+x.speed*2+x.crit*500+x.skillScale*100);}
export function teamPower(s:Save){const base=s.formation.reduce((a,id)=>a+heroPower(s.roster[id]),0);return Math.round(base*(1+activeBonds(s.formation).reduce((a,b)=>a+(b.atk||0)*.6+(b.hp||0)*.4,0)));}
export function levelCost(o:Owned){return{gold:180+o.level*85,exp:3+Math.floor(o.level*.9)};}
export function upgrade(s:Save,id:number,kind:'level'|'stars'|'ascend',count=1):{save:Save;message:string}{const n=clone(s),o=n.roster[id];if(!o)return{save:s,message:'尚未获得这位武将'};let total=0;for(let i=0;i<count;i++){if(kind==='level'){const c=levelCost(o);if(o.level>=40)break;if(n.gold<c.gold||n.exp<c.exp)break;n.gold-=c.gold;n.exp-=c.exp;o.level++;}else if(kind==='stars'){const shards=o.stars*20;if(o.stars>=5||o.shards<shards||n.gold<o.stars*1500)break;n.gold-=o.stars*1500;o.shards-=shards;o.stars++;}else{if(o.ascend>=4||o.level<(o.ascend+1)*5||n.stones<(o.ascend+1)*10||n.gold<(o.ascend+1)*2000)break;n.stones-=(o.ascend+1)*10;n.gold-=(o.ascend+1)*2000;o.ascend++;}total++;n.upgrades++;}return{save:total?n:s,message:total?`${HEROES[id].name}${kind==='level'?`提升 ${total} 级`:kind==='stars'?'升星成功':'突破成功'} · 战力 ${heroPower(o).toLocaleString()}`:'材料不足或已达上限，请查看所需资源'};}
export interface Pull {id:number;isNew:boolean;shards:number;rarity:string}
export function recruit(s:Save,count:1|10,mode:'premium'|'normal',rng=Math.random):{save:Save;pulls:Pull[];error?:string}{if(mode==='premium'?s.tickets<count:s.gold<count*1000)return{save:s,pulls:[],error:'招募资源不足，可通过征战或任务获得'};const n=clone(s);if(mode==='premium')n.tickets-=count;else n.gold-=count*1000;const pulls:Pull[]=[];for(let i=0;i<count;i++){n.pulls++;if(mode==='premium')n.pity++;let rarity='R';const r=rng();if(mode==='premium')rarity=r<.02?'UR':r<.14?'SSR':r<.6?'SR':'R';else rarity=r<.02?'SSR':r<.28?'SR':'R';if(mode==='premium'&&n.pity>=30&&rarity!=='UR')rarity='SSR';if(count===10&&i===9&&rarity==='R'&&pulls.every(p=>p.rarity==='R'))rarity='SR';if(mode==='premium'&&(rarity==='SSR'||rarity==='UR'))n.pity=0;const pool=HEROES.filter(h=>h.rarity===rarity);const h=pool[Math.floor(rng()*pool.length)];const isNew=!n.roster[h.id];const shards=rarity==='UR'?30:rarity==='SSR'?25:20;if(isNew){n.roster[h.id]={...own(h.id),shards:n.shardBank[h.id]||0};delete n.shardBank[h.id];}else n.roster[h.id].shards+=shards;pulls.push({id:h.id,isNew,shards:isNew?0:shards,rarity});}return{save:n,pulls};}
export function clearStage(s:Save,id:number,stars:number){const n=clone(s),st=STAGES[id],first=!n.cleared[id],newThree=stars===3&&(n.cleared[id]||0)<3;n.cleared[id]=Math.max(n.cleared[id]||0,stars);n.wins++;const rewards={gold:st.gold*(first?2:1),exp:st.exp*(first?2:1),stones:st.stones,tickets:(first?st.tickets:0)+(newThree?1:0),shards:first?10:4,hero:st.enemies[3]};n.gold+=rewards.gold;n.exp+=rewards.exp;n.stones+=rewards.stones;n.tickets+=rewards.tickets;if(n.roster[rewards.hero])n.roster[rewards.hero].shards+=rewards.shards;else{n.shardBank[rewards.hero]=(n.shardBank[rewards.hero]||0)+rewards.shards;if(n.shardBank[rewards.hero]>=40){n.roster[rewards.hero]={...own(rewards.hero),shards:n.shardBank[rewards.hero]-40};delete n.shardBank[rewards.hero];}}return{save:n,rewards};}
export function visibleRoster(s:Save){return Object.values(s.roster).filter(o=>o.shards>=0);}
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export const MISSIONS=[{id:'welcome',name:'初入云阙',desc:'启程的第一份赠礼',target:1,value:(s:Save)=>s.started?1:0,reward:{gold:5000,exp:100,tickets:10,stones:10}}, {id:'first',name:'初战告捷',desc:'赢得1场征战',target:1,value:(s:Save)=>s.wins,reward:{gold:3000,exp:80,tickets:5,stones:10}},{id:'recruit',name:'群星相逢',desc:'累计招募10次',target:10,value:(s:Save)=>s.pulls,reward:{gold:5000,exp:100,tickets:5,stones:10}},{id:'train',name:'锋芒初露',desc:'累计养成12次',target:12,value:(s:Save)=>s.upgrades,reward:{gold:8000,exp:120,tickets:5,stones:20}},...Array.from({length:5},(_,i)=>({id:`chapter${i}`,name:`征服·${['黄巾','虎牢','逐鹿','官渡','赤壁'][i]}`,desc:`通关第${i+1}章`,target:1,value:(s:Save)=>s.cleared[i*6+5]?1:0,reward:{gold:12000+i*5000,exp:200+i*80,tickets:10,stones:25}}))];
