'use client';
import {CSSProperties,ReactNode} from 'react';
import {HEROES,RARITY_COLOR,FACTION_COLOR} from './data';
import Character from './Character';
import {Owned,heroPower} from './state';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function Portrait({id,className='',style={}}:{id:number;className?:string;style?:CSSProperties}){return <div role="img" aria-label={HEROES[id].name} className={`portrait ${className}`} style={{backgroundImage:`url(/art/portraits/hero-${id}.webp)`,backgroundSize:'cover',backgroundPosition:'center',...style}}/>}
export function Stars({count=1,total=5}:{count?:number;total?:number}){return <span className="stars" aria-label={`${count}星`}>{Array.from({length:total},(_,i)=><span key={i} className={i<count?'lit':''}>★</span>)}</span>}
export function HeroCard({id,owned,onClick,selected=false,small=false,extra}:{id:number;owned?:Owned;onClick?:()=>void;selected?:boolean;small?:boolean;extra?:ReactNode}){const h=HEROES[id];return <button className={`hero-card ${small?'small':''} ${selected?'selected':''} ${!owned?'unowned':''}`} style={{'--rarity':RARITY_COLOR[h.rarity],'--faction':FACTION_COLOR[h.faction]} as CSSProperties} onClick={onClick} aria-label={`${h.name}${owned?' 等级 '+owned.level:' 未获得'}`}><span className="character-pedestal" aria-hidden="true"/><Character id={id}/><span className="rarity">{h.rarity}</span><span className="faction-seal">{h.faction}</span><div className="hero-caption"><strong>{h.name}</strong><span>{owned?`Lv.${owned.level} · ${h.role}`:h.role}</span><Stars count={owned?.stars||0}/>{!small&&<small>{owned?`战力 ${heroPower(owned).toLocaleString()}`:'尚未获得'}</small>}</div>{extra}</button>}
export function Modal({open,onClose,title,description,children,className=''}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode;className?:string}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={`game-modal ${className}`}><DialogTitle className="modal-title">{title}</DialogTitle><DialogDescription className={description?'modal-desc':'sr-only'}>{description||title}</DialogDescription>{children}</DialogContent></Dialog>}
export function PageHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children?:ReactNode}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{children}</div>}
