import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import * as THREE from 'three';
fs.mkdirSync('.sites-runtime',{recursive:true});const temp=fs.mkdtempSync(path.resolve('.sites-runtime/model-test-'));
try{
 for(const name of ['data','state','battle','choreography','heroModels']){const source=fs.readFileSync(new URL(`../game/${name}.ts`,import.meta.url),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,(_,p)=>`from '${p}.mjs'`);fs.writeFileSync(path.join(temp,name+'.mjs'),js);}
 const {createHeroRig,animateHeroRig}=await import(path.join(temp,'heroModels.mjs'));const before=performance.now();let triangles=0,maxDrawCalls=0;const signatures=new Set();
 for(let id=0;id<24;id++){const rig=createHeroRig(id);rig.root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(rig.root),size=bounds.getSize(new THREE.Vector3());assert.ok(size.x>.7&&size.y>2&&size.z>.4,`hero ${id} must have real volume`);assert.ok(rig.meshes.every(m=>m.geometry.type!=='PlaneGeometry'));assert.ok(rig.meshes.length<30);maxDrawCalls=Math.max(maxDrawCalls,rig.meshes.length);for(const mesh of rig.meshes)triangles+=mesh.geometry.attributes.position.count/3;
 signatures.add(rig.root.userData.weaponType+'-'+rig.meshes.map(m=>Array.from(m.geometry.attributes.color.array).slice(0,18).join(',')).join('|'));
 for(const [w,h] of [[1440,659],[768,771],[390,591],[375,414]]){const aspect=w/h,camera=new THREE.PerspectiveCamera(42,aspect,.1,80),d=Math.max(15.2,14.8/(2*Math.tan(21*Math.PI/180)*aspect));camera.position.set(0,d*.55,d*.84);camera.lookAt(0,.55,0);camera.updateMatrixWorld();for(const side of [-1,1])for(const z of [-3.23,3.23]){for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const depth of [bounds.min.z,bounds.max.z]){const v=new THREE.Vector3(side*4.15+x,y,z+depth).project(camera);assert.ok(Math.abs(v.x)<1&&Math.abs(v.y)<1,`hero ${id} out of ${w}x${h} frustum: ${v.x},${v.y}`);}}}
 const idle=rig.rightArm.rotation.x;animateHeroRig(rig,{time:0,windup:1,strike:1});assert.notEqual(rig.rightArm.rotation.x,idle);rig.root.updateMatrixWorld(true);const tip=new THREE.Vector3();rig.weaponTip.getWorldPosition(tip);assert.ok([tip.x,tip.y,tip.z].every(Number.isFinite));if([0,1,2,8,9,14,18].includes(id))assert.ok(tip.z>.2,'attack weapon must swing forward');rig.root.rotation.y=Math.PI/2;rig.root.updateMatrixWorld(true);const turned=new THREE.Box3().setFromObject(rig.root);assert.ok(!turned.equals(bounds));rig.dispose();}
 const initMs=Math.round(performance.now()-before);assert.equal(signatures.size,24);
 const audio=fs.readdirSync('public/audio/kenney').filter(n=>n.endsWith('.mp3'));assert.equal(audio.length,8);const audioBytes=audio.reduce((n,x)=>n+fs.statSync('public/audio/kenney/'+x).size,0);assert.ok(audioBytes<100000);
 assert.ok(!fs.readFileSync('game/BattleStage.tsx','utf8').includes('TextureLoader'));
 for(const file of ['game/Game.tsx','game/ui.tsx','app/globals.css','app/characters.css'])assert.ok(!/\/art\/(citadel|portraits|zhaoyun)\.png/.test(fs.readFileSync(file,'utf8')));
 const firstImages=['public/art/optimized/citadel.webp','public/art/optimized/zhaoyun.webp','public/art/portraits/hero-0.webp'].reduce((n,f)=>n+fs.statSync(f).size,0);assert.ok(firstImages<750000);
 console.log(JSON.stringify({result:'PASS',volumetricHeroes:24,distinctProfiles:signatures.size,allHeroTriangles:triangles,maxDrawCallsPerHero:maxDrawCalls,modelGenerationMsFor24:initMs,combatCharacterTextureRequests:0,initialArtBytes:firstImages,audioFiles:audio.length,audioBytes,articulationAndTurning:true},null,2));
}finally{fs.rmSync(temp,{recursive:true,force:true});}
